name: Kosli Complete Action
description:
  This action checks if a Kosli trail is complete by looking for attestations
  with a specific status.
author: Kosli Dev Team

# Define your inputs here.
inputs:
  json_file_path:
    description: The path to the JSON file containing the trail data.
    required: true
  status_to_find:
    description:
      The status to look for in the attestations (e.g., "MISSING", "COMPLETE").
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if JSON file exists
      run: |
        if [ ! -f ${{ inputs.json_file_path }} ]; then
          echo "Error: JSON file not found at ${{ inputs.json_file_path }}"
          exit 1
        fi
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: run check-template-complete-action
      run: check-template-complete.sh ${{ inputs.json_file_path }} ${{ inputs.status_to_find }}
      shell: bash
