name: begin trail action
description:
  This action begins a Kosli trail by creating a new trail with the specified
  parameters.
author: Kosli Dev Team



# Define your inputs here.
inputs:
  build_id:
    description: The ID of the build to check.
    required: true

runs:
  using: "composite"
  steps:
    - name: setup-kosli-cli
      uses: kosli-dev/setup-cli-action@v2
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: run begin trail
      run: kosli begin trail ${{ github.sha }} --description "build number ${BUILD_NUMBER}" --template-file flow.yaml
      shell: bash
