name: Kosli Complete Action
description:
  This action checks if a Kosli trail is complete by looking for attestations
  with a specific status.
author: Kosli Dev Team

# Define your inputs here.
inputs:
  json_file_path:
    description: The path to the JSON file containing the trail data.
    required: true
  status_to_find:
    description: The status to look for in the attestations (e.g., "MISSING", "COMPLETE").
    required: true

runs:
  using: "node20"
  main: dist/entrypoint.js
